name: Build container images

on:
  workflow_dispatch:
    inputs:
      target:
        description: Target ID or all
        required: false
        default: all
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "minimal probe"
